#!/usr/bin/env python3
import argparse

from lib.parser_factory import ParserFactory
from lib.subnet_manager import SubnetManager

title = 'A tiny command line utility for querying IP addresses of the host machine.'
parser = argparse.ArgumentParser(description = title)

parser.add_argument(
    '--with-prefix',
    help = 'Print addressess with CIDR notation',
    action = 'store_true'
)

parser.add_argument(
    '--overlapping',
    help = 'List only overlapping subnets',
    action = 'store_true'
)

args = parser.parse_args()

# instantiate parser and subnet manager
factory = ParserFactory()
parser = factory.get_parser()
sm = SubnetManager()

# get addresses
address_tuples = parser.parse_ipv4_addresses()

if args.overlapping == False:
    print("\n".join(sm.get_addresses(address_tuples, args.with_prefix)))
else:
    sets = sm.get_overlapping_subnets(address_tuples)

    # separate overlapping pairs with a double new-line
    print("\n\n".join(["\n".join(set) for set in sets]))