#!/usr/bin/env python3
import argparse
import subprocess

from lib.ifconfig_parser import IfconfigParser
from lib.subnet_manager import SubnetManager

if __name__ == '__main__':
    title = 'A tiny command line utility for querying IP addresses of the host machine.'
    parser = argparse.ArgumentParser(description = title)

    parser.add_argument(
        '--with-prefix',
        help = 'Print addressess with CIDR notation',
        action = 'store_true'
    )

    parser.add_argument(
        '--overlapping',
        help = 'List only overlapping subnets',
        action = 'store_true'
    )

    args = parser.parse_args()
    ifconfig_output = subprocess.getoutput(["ifconfig"])

    # instantiate parser and subnet manager
    p = IfconfigParser(ifconfig_output)
    sm = SubnetManager()

    # get addresses
    address_tuples = p.parse_ipv4_addresses()

    if args.overlapping == False:
        print("\n".join(sm.pluck_address(address_tuples, args.with_prefix)))
    else:
        print("\n".join(sm.get_overlapping_subnets(address_tuples)))