#!/usr/bin/env python3
import argparse
import subprocess
import ipaddress

from lib.ifconfig_parser import IfconfigParser
from lib.subnet_manager import SubnetManager

if __name__ == '__main__':
    title = 'A tiny command line utility for querying IP addresses of the host machine.'
    parser = argparse.ArgumentParser(description = title)

    parser.add_argument(
        '--with-prefix',
        help = 'Print addressess with CIDR notation',
        action = 'store_true'
    )

    parser.add_argument(
        '--overlapping',
        help = 'List only overlapping subnets',
        action = 'store_true'
    )

    args = parser.parse_args()

    ifconfig_output = subprocess.getoutput(["ifconfig"])
    p = IfconfigParser(ifconfig_output)

    address_tuples = p.parse_ipv4_addresses()

    sm = SubnetManager()

    print("\n".join(sm.pluck_address(address_tuples, True)))

    # build a list of Networks using the ip_network factory function
    networks = [ipaddress.ip_network(addr, False) for addr in sm.pluck_address(address_tuples, True)]

    print([n.network_address for n in networks])

    print(sm.get_overlapping_subnets(networks))